name: 'Hello World'
description: 'Greet someone'
inputs:
  dd-api-key: # id of input
    description: 'DD'
    required: true
    default: ''
outputs:
  random-number:
    description: 'Random number'
    value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: 'composite'
  steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      shell: bash
    - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      shell: bash
    - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      shell: bash
    - name: Check out repository code
      uses: actions/checkout@v3
    - run: echo "💡 The ${{ github.repository }} at ${{ github.head_ref }} repository has been cloned to the runner."
      shell: bash
    - run: echo "💡 The ${{ github.repository_owner }} is the owner of repository."
      shell: bash
    - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      shell: bash
    - name: List files in the repository
      shell: bash
      run: |
        ls ${{ github.workspace }}
    - run: echo "🍏 This job's status is ${{ job.status }}."
      shell: bash
    - name: DD action
      uses: int128/datadog-actions-metrics@v1
      with:
        datadog-api-key: ${{ inputs.dd-api-key }}
        collect-job-metrics: true
    - name: Build count
      uses: masci/datadog@v1
      with:
        api-key: ${{ inputs.dd-api-key }}
        metrics: |
          - type: "count"
            name: "test.runs.count"
            value: 1.0
            host: ${{ github.repository_owner }}
            tags:
              - "project:${{ github.repository }}"
              - "branch:${{ github.head_ref }}"
